config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  get 'tasks/:id/complete', to: 'tasks#complete', as: 'task_complete'
  resources :tasks, only: [:index, :show]
  root 'tasks#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :user_tasks
  has_many :users, through: :user_tasks

    def completed_for?(user)
        user_task = self.user_tasks.find_by(user: user)

        user_task.present? && user_task.completed
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_tasks
  has_many :tasks, through: :user_tasks       
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :authenticate_user!


  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
    @users = User.find_by(id: current_user.id)
  end

  def complete
    task = Task.find(params[:id])


    user_task = task.user_tasks.find_by(user: current_user)

    if user_task == nil
      UserTask.create(user: current_user, task: task, completed: true)
    else

      user_task.completed = !user_task.completed

      user_task.save
    end

    redirect_to tasks_path
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
    @users = User.find_by(id: current_user.id)
    @task = Task.find(params[:id])
    @user_tasks = UserTask.where(task: @task).order(updated_at: :desc).limit(5)
    @user_task = UserTask.where(task: @task).order(updated_at: :desc)
  end

  # GET /tasks/new

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba18</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar'%>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Tareas del 18</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <% if user_signed_in? %>
                <li class="nav-item">
                    <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
                </li>
                <li>
                  Tareas Realizadas: <%= @users.tasks.count %>
                </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% task.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<div class="row">
    <% @tasks.each do |task| %>
        <div class="col-md-4">
            <%= image_tag task.photo, class: 'img-fluid' %>
            <h1>
                <%= link_to task.title, task_path(id: task.id) %>
            </h1>
            <p><%= task.description %></p>
            <% if task.completed_for?(current_user) %>
                <%= link_to "No listo", task_complete_path(id: task.id), class: 'btn btn-danger' %>
            <% else %>
                <%= link_to "Listo", task_complete_path(id: task.id), class: 'btn btn-success' %>
            <% end %>
        </div>
    <% end %>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form', task: @task %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <h2>Top 5</h2>
      <div class="row">
        <ul>
            <% @user_tasks.each do |user_task| %>
            
            <div class="col-md-6">
                <li><%= user_task.user.email %></li>
            </div>
            <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <h2>Usuarios</h2>
      <ul>
        <% @user_task.each do |user| %>
          <li><%= user.user.email %></li>
        <% end %>
      </ul>
    </div>
  </div>
</div>


<%= link_to 'Back', tasks_path %>